### ISSUE TITLE
/network/status BlockIdentifier

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin#3]
[NetworkStatus](https://github.com/Zondax/lotus/blob/rosetta_integration/rosetta/services/network.go#L89-L96) currently returns the CID of the very first Block instead of using a unique identifier from the entire TipSet. 

A helper method that takes a TipSet and calculates the hash of the entire TipSet which includes multiple Blocks would be very helpful.

**Comment by raynaudoe** [comment]
Ok, a few considerations:

The input parameters for `/block`, can be of type `request.BlockIdentifier.Index` or `request.BlockIdentifier.Hash`. 
With `index` there's no problem on its interpretation.

`Hash` on the other hand, must be a proper `TipSetKey` typed value, since inside Lotus there are no hashed `TipSets`, it is not feasible to search for a TipSet by calculating its hashed value.

So in order to keep consistency, since its what Lotus provides, we can only return on `/network/status` and on `/block` the `TipSetKey` of the genesis/current TipSet as is stored on chain. But, if you have any restrictions on the size of the returned `Hash` value (since `TipSetKey` is length variable), we should ask Lotus for modifications.

**Comment by qiwu7** [comment]
> The input parameters for /block, can be of type request.BlockIdentifier.Index or request.BlockIdentifier.Hash.
With index there's no problem on its interpretation. Hash on the other hand, must be a proper TipSetKey typed value, since inside Lotus there are no hashed TipSets, it is not feasible to search for a TipSet by its hashed value.

I think it's fine that we won't be able to lookup a tipset using a `BlockIdentifier.Hash`

> So in order to keep consistency, since its what Lotus provides, we can only return on /network/status and on /block the TipSetKey of the genesis/current TipSet as is stored on chain. But, if you have any restrictions on the size of the returned Hash value (since TipSetKey is length variable), we should ask Lotus for modifications.

you should be able to calculate the hash of a slice of block CIDs to represent a tipSet

**Comment by jleni** [comment]
Lotus indexes using TipSetKey (the concatenation of CIDs).
We can calculate the hash of the CIDs in the tipset, however, later on we cannot use that as a key to look for tipsets. 

So we have two alternatives:
- We return complete TipSetKeys (variable lenght)
- We hash it but we need to extend Lotus to have and additional index (  HashTipSetKey -> TipSetKey)
